### ISSUE TITLE
Add new video-game quotes

### ISSUE THREAD

**Issue by kilgamesh** [kilgamesh/ultima#2]
Remove and then add additional quotes to the data/quotes.json following the same schema.

**Comment by joseph-macfarlane** [comment]
where is your data/quotes.json file?

**Comment by 0hundred0** [comment]
You can find it in the “migrate” branch. 

Best,
K. Richmond

**Comment by 0hundred0** [comment]
If you have game suggestions or very specific quote requests, please use the discussion board found [here](https://github.com/0hundred0/ultima/discussions/1). I would rather add a larger batch of quotes to the database at once.

Once again, all contributors and users are greatly appreciated!

**Comment by 0hundred0** [comment]
Those looking to contribute quotes to the API documentation can be found [here](https://github.com/0hundred0/ultima/blob/migrate/CONTRIBUTING.md)!

**Comment by kilgamesh** [comment]
Removed database management branch. Checkout the database repository [here](https://github.com/kilgamesh/ultima-db)
