### ISSUE TITLE
Endpoint to fetch quote from specific game

### ISSUE THREAD

**Issue by CBeatt13** [Kilgamesh/ultima#53]
I want to make a plugin for my video game frontend of choice that I can use to show quotes from the game selected but I see no way currently do to so with the endpoints available. It'd be nice if I could pass a Platform and Title string into a search endpoint that looks for the game in the database and returns a quote if one is available.

**Comment by CBeatt13** [comment]
Opened the ticket too soon. I do see you have a game title search. I'm not real clear if you are only curating quotes from PC games or not though and whether the platform parameter is even a thing that would be needed in your dataset.

**Comment by Kilgamesh** [comment]
I did consider it but if enough people requested the platform I would add it. As of now it seems unnecessary. 

As of now, most of the games added are RPGs & Shooters though there are a other genres sprinkled in there. I am planning on adding multiple parameter endpoints in the next update, but thank you for bringing it to my attention!
